version: "3"
services:
  db:
    image: mariadb:10.2
    container_name: db
    environment:
      MYSQL_DATABASE: laravel-boilerplate
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
volumes:
  db: